@ExpenseTracker_Api_HostAddress = https://localhost:7007

### Obține toate categoriile

GET {{ExpenseTracker_Api_HostAddress}}/api/categories
Accept: application/json

###

### Adaugă o categorie

POST {{ExpenseTracker_Api_HostAddress}}/api/categories
Content-Type: application/json

{
  "name": "Transport"
}